database:
  url: "jdbc:mysql://localhost:3306/openmccore"
  user: "root"
  password: "password"
rtp:
  cooldown: 60
  cooldown-error: 5
  minx: -3000
  maxx: 3000
  minz: -3000
  maxz: 3000
  rtp_wand: "wand:rtpwand"
  max_try: 3
feed:
  cooldown: 60
spawn:
  x: 5611.5
  y: 65.0
  z: 1226.5
  world: world
deco_freeze_nombre_de_jours_ban: 30